server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:db

traced-in:
  service-name: tracedin-service
  base-package: com.univ.tracedinservice
  exporter: traced-in
  endpoint: http://localhost:8989/api/v1/spans
  sampling: 0.5