server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:db
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: hello-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

traced-in:
  service-name: tracedin-service
  base-package: com.univ.tracedinservice
  exporter: traced-in
  project-key: 1206887328-a7863a66-528e-4f37-b805-04e1314fb924
  sampling: 1
  metric-interval: 10
  span-endpoint: http://localhost:8989/api/v1/spans
  metric-endpoint: http://localhost:8989/api/v1/metrics