spring:
  datasource:
    url: jdbc:h2:mem:db
  kafka:
    producer:
      bootstrap-servers:
        - localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

traced-in:
  service-name: tracedin-client
  base-package: com.univ.tracedinclient
  project-key: 1206887328-a7863a66-528e-4f37-b805-04e1314fb924
  sampling: 1
  metric-interval: 10
  host: localhost

  demo:
    service:
      url: http://localhost:8081

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.http.client: DEBUG
