spring:
  datasource:
    url: jdbc:h2:mem:db

traced-in:
  service-name: tracedin-client
  base-package: com.univ.tracedinclient
  exporter: traced-in
  sampling: 0.5
  endpoint: http://localhost:8989/api/v1/spans

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.http.client: DEBUG