name: push

on:
  push:
    branches: [ 'main' ]
    paths:
      - 'tracedin-sdk/**'

defaults:
  run:
    working-directory: tracedin-sdk
    shell: bash

env:
  JAVA_VERSION: '17'
  DISTRIBUTION: 'temurin'

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          checkstyle_config: google_checks.xml

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Run Gradle tests
        run: ./gradlew test

  codeql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
