name: release

on:
  push:
    branches: ['build']
    tags:
      - 'v*'

env:
  JAVA_VERSION: '17'
  DISTRIBUTION: 'temurin'

defaults:
  run:
    working-directory: tracedin-sdk
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Import GPG Keys
        run: |
          gpg --keyserver keyserver.ubuntu.com --recv-keys ${{ secrets.GPG_KEYS }}
          gpg --default-key ${{ secrets.GPG_KEYS }}
          gpg --list-secret-keys

      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY_PASSWORD }}
        run: ./gradlew publishToMavenCentral --no-configuration-cache

