name: Release

on:
  push:
    tags:
      - 'v*'

env:
  JAVA_VERSION: '17'
  DISTRIBUTION: 'temurin'

defaults:
  run:
    working-directory: tracedin-sdk

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}

      - name: Build with Gradle
        run: ./gradlew clean build

  publish:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: ./gradlew publishToMavenCentral --no-configuration-cache

